### ISSUE TITLE
Dolmen warning on reserved solver-generated function symbols

### ISSUE THREAD

**Issue by Tomaqa** [SMT-LIB/benchmark-submission-2024#12]
On my benchmarks, dolmen produces warnings such as:
```
Shadowing: `.def_1066` is reserved for solver-generated function symbols other than abstract values
```
Is this a problem in SMT-COMP?

**Comment by hansjoergschurr** [comment]
Yes, SMT-LIB problems should not use such symbols, because the solvers should be free to introduce symbols that start with `.` without having to worry that there is a name-clash with input symbols.
Usually it is enough to systematically rename such symbols using `sed`.

**Comment by Tomaqa** [comment]
OK. It would be nice if the README states explicitly that not only errors but also warnings of dolmen count.

**Comment by hansjoergschurr** [comment]
This is a good point.
I believe the best option would be to have an option in Dolmen that makes this an error.
I will bring this up with the Dolmen maintainers, and we will improve this aspect for next years submission system.
