### ISSUE TITLE
`incremental/QF_UF/20190906-CLEARSY` use `set logic UF`

### ISSUE THREAD

**Issue by Tomaqa** [SMT-LIB/benchmark-submission-2024#17]
I am not sure if this is the right place, but I discovered that benchmarks `incremental/QF_UF/20190906-CLEARSY`, probably introduced earlier, do not set logic to `QF_UF` but to `UF`, which does not match the intended logic. I suppose this should be fixed?

**Comment by mpreiner** [comment]
This is now fixed in the 2024.05.13 release for the incremental benchmarks: https://zenodo.org/records/11186591
