### ISSUE TITLE
Older SMT-LIB Benchmarks Unavailable

### ISSUE THREAD

**Issue by anirjoshi** [SMT-LIB/benchmark-submission-2024#18]
Hi, it looks like the [StarExec](https://www.starexec.org/starexec/secure/explore/spaces.jsp?id=239) listed on the [SMT-LIB page](https://smt-lib.org/benchmarks.shtml) for accessing older benchmarks is unavailable.

PS: If this is not the right place to ask such queries, please point me to the right community.

**Comment by anirjoshi** [comment]
Thank You, I am able to access it now.

**Comment by hansjoergschurr** [comment]
The latest release of the SMT-LIB benchmark that is available on [Zenodo](https://zenodo.org/communities/smt-lib/records) also includes old benchmarks.  We expect most people to work with the latest release.  The historical releases might be interesting for people that want to study how the benchmark library developed.
